- id: '1605301200380'
  alias: Mushroom Thermostat Off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.sensor_cluster_001_temperature
    above: '78'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.water_heater
  mode: single
- id: '1605301799433'
  alias: Mushroom Thermostat On
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.sensor_cluster_001_temperature
    below: '75'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.water_heater
  mode: single
- id: '1605996636638'
  alias: Christmas lights on
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-1:00:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.front_christmas_lights
  - service: light.turn_on
    data: {}
    entity_id: light.patio_lights
  mode: single
- id: '1605996753817'
  alias: Christmas lights off
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:30:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.front_christmas_lights
  - service: light.turn_off
    data: {}
    entity_id: light.patio_lights
  mode: single
- id: '1606788686752'
  alias: Grow light on
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.grow_light
  mode: single
- id: '1606788869716'
  alias: Grow light off
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.grow_light
  mode: single
- id: '1607113688393'
  alias: mushroom fan timer
  description: ''
  trigger:
  - platform: time_pattern
    hours: /12
  condition: []
  action:
  - service: script.run_mushroom_grow_fan
    data: {}
  mode: single
- id: '1607213412038'
  alias: printer done notification
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.vulcan_current_state
    from: Printing
    to: Operational
  condition:
  - condition: numeric_state
    entity_id: sensor.vulcan_job_percentage
    above: '99'
  action:
  - service: notify.mobile_app_pixel_3_xl
    data:
      message: 3d print is done
  mode: single
- id: '1608391405182'
  alias: Guest Bathroom light  off
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.guest_bathroom_lightswitch
  mode: single
- id: '1608391724492'
  alias: Guest Bathroom light  on
  description: ''
  trigger:
  - platform: time
    at: '7:00'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.guest_bathroom_lightswitch
  mode: single
- id: '1609537594303'
  alias: Stir Plate On
  description: ''
  trigger:
  - platform: time
    at:
    - 07:00
    - '19:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.stir_plate
  - delay: 00:05
  - service: switch.turn_off
    data: {}
    entity_id: switch.stir_plate
  mode: single
- id: '1614340423197'
  alias: greenhouse fan timer
  description: ''
  trigger:
  - platform: time_pattern
    hours: /12
  condition: []
  action:
  - service: script.run_greenhouse_fan
    data: {}
  mode: single
- id: '1617671753171'
  alias: Trash day notification
  description: ''
  trigger:
  - platform: time
    at: '21:00'
  condition:
  - condition: time
    weekday:
    - tue
  action:
  - service: notify.mobile_app_pixel_3_xl
    data:
      title: Trash day!
      message: Tomorrow is trash day. Did you take out the trash yet?
  - service: notify.mobile_app_pixel_3
    data:
      title: Trash day!
      message: Tomorrow is trash day. Did you take out the trash yet?
  mode: single
- id: '1617828682585'
  alias: Washer Notification
  trigger:
  - platform: state
    entity_id: sensor.washing_machine_running
    from: 'On'
    to: 'Off'
    for: 0:00:10
  condition:
  - condition: template
    value_template: '{{ (now() | as_timestamp) - (trigger.from_state.last_changed
      | as_timestamp) > 60 }}

      '
  action:
  - service: notify.mobile_app_pixel_3_xl
    data:
      title: Washer is done
      message: Washer is done
  - service: notify.mobile_app_pixel_3
    data:
      title: Washer is done
      message: Washer is done
  mode: single
- id: '1617829455735'
  alias: Dryer Notification
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.dryer_running
    from: 'On'
    to: 'Off'
    for: 0:00:10
  condition:
  - condition: template
    value_template: '{{ (now() | as_timestamp) - (trigger.from_state.last_changed
      | as_timestamp) > 60 }}'
  action:
  - service: notify.mobile_app_pixel_3_xl
    data:
      title: Dryer is done
      message: Dryer is done
  - service: notify.mobile_app_pixel_3
    data:
      title: Dryer is done
      message: Dryer is done
  mode: single

- id: '1761284125831'
  alias: Work Bench Lights Auto On/Off
  description: 'Switch workbench lights with basement lights'
  trigger:
    - platform: state
      entity_id: light.basement_lightswitch
  action:
    - service_template: >
        {% if trigger.to_state.state == 'on' and trigger.from_state.state == 'off' %}
          light.turn_on
        {% elif trigger.to_state.state == 'off' and trigger.from_state.state == 'on' %}
          light.turn_off
        {% endif %}
      entity_id: 
        - light.workbench_lights
        - light.basement_light_001
        - light.basement_light_002
        - light.basement_light_003
        - light.basement_light_004
        - light.basement_light_005
        - light.basement_light_006
        - light.basement_light_007
  mode: single
