- id: '1605301200380'
  alias: Mushroom Thermostat Off
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.sensor_cluster_001_temperature
    above: '78'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.water_heater
  mode: single
- id: '1605301799433'
  alias: Mushroom Thermostat On
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.sensor_cluster_001_temperature
    below: '75'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.water_heater
  mode: single
- id: '1605996636638'
  alias: Christmas lights on
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-1:00:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.front_christmas_lights
  - service: light.turn_on
    data: {}
    entity_id: light.patio_lights
  mode: single
- id: '1605996753817'
  alias: Christmas lights off
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:30:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.front_christmas_lights
  - service: light.turn_off
    data: {}
    entity_id: light.patio_lights
  mode: single
- id: '1606788686752'
  alias: Grow light on
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.grow_light
  mode: single
- id: '1606788869716'
  alias: Grow light off
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.grow_light
  mode: single
- id: '1607113688393'
  alias: mushroom fan timer
  description: ''
  trigger:
  - platform: time_pattern
    hours: /12
  condition: []
  action:
  - service: script.run_mushroom_grow_fan
    data: {}
  mode: single
- id: '1607213412038'
  alias: printer done notification
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.vulcan_current_state
    from: Printing
    to: Operational
  condition:
  - condition: numeric_state
    entity_id: sensor.vulcan_job_percentage
    above: '99'
  action:
  - service: notify.mobile_app_pixel_3_xl
    data:
      message: 3d print is done
  mode: single
- id: '1608391405182'
  alias: Guest Bathroom light  off
  description: ''
  trigger:
  - platform: time
    at: '19:00'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.guest_bathroom_light
  mode: single
- id: '1608391724492'
  alias: Guest Bathroom light  on
  description: ''
  trigger:
  - platform: time
    at: '7:00'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.guest_bathroom_light
  mode: single
- id: '1609537594303'
  alias: Stir Plate On
  description: ''
  trigger:
  - platform: time
    at:
    - 07:00
    - '19:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.stir_plate
  - delay: 00:05
  - service: switch.turn_off
    data: {}
    entity_id: switch.stir_plate
  mode: single
- id: '1614340423197'
  alias: greenhouse fan timer
  description: ''
  trigger:
  - platform: time_pattern
    hours: /12
  condition: []
  action:
  - service: script.run_greenhouse_fan
    data: {}
  mode: single
- id: '1617671753171'
  alias: Trash day notification
  description: ''
  trigger:
  - platform: time
    at: '21:00'
  condition:
  - condition: time
    weekday:
    - tue
  action:
  - service: notify.mobile_app_pixel_3_xl
    data:
      title: Trash day!
      message: Tomorrow is trash day. Did you take out the trash yet?
  - service: notify.mobile_app_pixel_3
    data:
      title: Trash day!
      message: Tomorrow is trash day. Did you take out the trash yet?
  mode: single
- id: '1617828682585'
  alias: Washer Notification
  trigger:
  - platform: state
    entity_id: sensor.washing_machine_running
    from: 'On'
    to: 'Off'
    for: 0:00:10
  condition:
  - condition: template
    value_template: '{{ (now() | as_timestamp) - (trigger.from_state.last_changed
      | as_timestamp) > 60 }}

      '
  action:
  - service: notify.mobile_app_pixel_3_xl
    data:
      title: Washer is done
      message: Washer is done
  - service: notify.mobile_app_pixel_3
    data:
      title: Washer is done
      message: Washer is done
  mode: single
- id: '1617829455735'
  alias: Dryer Notification
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.dryer_running
    from: 'On'
    to: 'Off'
    for: 0:00:10
  condition:
  - condition: template
    value_template: '{{ (now() | as_timestamp) - (trigger.from_state.last_changed
      | as_timestamp) > 60 }}'
  action:
  - service: notify.mobile_app_pixel_3_xl
    data:
      title: Dryer is done
      message: Dryer is done
  - service: notify.mobile_app_pixel_3
    data:
      title: Dryer is done
      message: Dryer is done
  mode: single
- id: '1761284125831'
  alias: Work Bench Lights Auto On/Off
  description: Switch workbench lights with basement lights
  trigger:
  - platform: state
    entity_id: light.basement_light
  action:
  - service_template: "{% if trigger.to_state.state == 'on' and trigger.from_state.state\
      \ == 'off' %}\n  light.turn_on\n{% elif trigger.to_state.state == 'off' and\
      \ trigger.from_state.state == 'on' %}\n  light.turn_off\n{% endif %}\n"
    entity_id:
    - light.workbench_lights
    - light.basement_light_001
    - light.basement_light_002
    - light.basement_light_003
    - light.basement_light_004
    - light.basement_light_005
    - light.basement_light_006
    - light.basement_light_007
  mode: single
- id: '1619665115071'
  alias: Office Light Long Press
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    for: '0:00:00.4'
    entity_id: binary_sensor.office_lightswitch_button
  condition: []
  action:
  - choose:
    - conditions:
      - condition: device
        type: is_on
        device_id: b7bde0b989a2b902e4a6f6cc65d71ab8
        entity_id: light.office_light
        domain: light
      sequence:
      - type: turn_on
        device_id: 3d499e898d453aa4e993adf5b46bd955
        entity_id: light.blue_desk_lamp
        domain: light
    - conditions:
      - condition: device
        type: is_off
        device_id: b7bde0b989a2b902e4a6f6cc65d71ab8
        entity_id: light.office_light
        domain: light
      sequence:
      - type: turn_off
        device_id: 3d499e898d453aa4e993adf5b46bd955
        entity_id: light.blue_desk_lamp
        domain: light
    default: []
  mode: single
- id: '1619838054001'
  alias: Office HVAC Booster On
  description: Turn on the office HVAC booster fan when the Nest reports HVAC is on
  trigger:
  - platform: state
    entity_id: climate.living_room
    attribute: hvac_action
    from: 'off'
    to: heating
  - platform: state
    entity_id: climate.living_room
    attribute: hvac_action
    from: 'off'
    to: cooling
  condition: []
  action:
  - type: turn_on
    device_id: cd1546f4ef60961315c7c545bf9eb757
    entity_id: switch.office_hvac_booster
    domain: switch
  mode: single
- id: '1619838104737'
  alias: Office HVAC Booster Off
  description: Turn off the office HVAC booster fan when the Nest reports HVAC is
    off
  trigger:
  - platform: state
    entity_id: climate.living_room
    attribute: hvac_action
    to: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: cd1546f4ef60961315c7c545bf9eb757
    entity_id: switch.office_hvac_booster
    domain: switch
  mode: single
- id: '1619838168234'
  alias: Vulcan Printing Done
  description: Notification when 3D printer finishes
  trigger:
  - platform: state
    entity_id: binary_sensor.vulcan_printing
    from: Printing
    to: Operational
  action:
  - service: notify.mobile_app_pixel_3_xl
    data:
      title: Vulcan has finished printing.
      message: Vulcan has finished printing after an elapsed time of {{states('sensor.vulcan_time_elapsed_friendly')}}
  mode: single
- id: '1619831689512'
  alias: Kitchen Task Lights Button
  description: Switch kitchen task lghts with remote button
  trigger:
  - type: turned_on
    platform: device
    device_id: 4cc524fbec3b232ae9761fbe9a9e9201
    entity_id: binary_sensor.kitchen_extra_switch_button
    domain: binary_sensor
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: device
          type: is_off
          device_id: 582b914cefacf15319e295aa3212535c
          entity_id: light.kitchen_sink_light_dimmer
          domain: light
        - condition: device
          type: is_off
          device_id: c3e43eeb2165593bce23f1c3291e28cd
          entity_id: light.kitchen_under_cabinet_lights_dimmer
          domain: light
      sequence:
      - type: turn_on
        device_id: 582b914cefacf15319e295aa3212535c
        entity_id: light.kitchen_sink_light_dimmer
        domain: light
      - type: turn_on
        device_id: c3e43eeb2165593bce23f1c3291e28cd
        entity_id: light.kitchen_under_cabinet_lights_dimmer
        domain: light
    - conditions:
      - condition: and
        conditions:
        - condition: device
          type: is_on
          device_id: 582b914cefacf15319e295aa3212535c
          entity_id: light.kitchen_sink_light_dimmer
          domain: light
        - condition: device
          type: is_on
          device_id: c3e43eeb2165593bce23f1c3291e28cd
          entity_id: light.kitchen_under_cabinet_lights_dimmer
          domain: light
      sequence:
      - type: turn_off
        device_id: 582b914cefacf15319e295aa3212535c
        entity_id: light.kitchen_sink_light_dimmer
        domain: light
      - type: turn_off
        device_id: c3e43eeb2165593bce23f1c3291e28cd
        entity_id: light.kitchen_under_cabinet_lights_dimmer
        domain: light
  mode: single
- id: '1619831682485'
  alias: Pantry light timer
  trigger:
  - platform: state
    entity_id: light.pantry_light
    to: 'on'
    for:
      minutes: 10
  action:
  - service: light.turn_off
    entity_id: light.pantry_light
- id: '1619831695314'
  alias: Closet light timer
  trigger:
  - platform: device
    type: turned_on
    device_id: da5ee33d92f0a23d1d287e178976695d
    entity_id: light.closet_light
    domain: light
    for:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  action:
  - type: turn_off
    device_id: da5ee33d92f0a23d1d287e178976695d
    entity_id: light.closet_light
    domain: light
  mode: single
- id: '1619831632648'
  alias: Bathroom light timer
  trigger:
  - platform: device
    type: turned_on
    device_id: c8ae982a520cbfe26c2754fdbcb8112d
    entity_id: light.bathroom_light
    domain: light
    for:
      hours: 1
      minutes: 30
      seconds: 0
      milliseconds: 0
  action:
  - type: turn_off
    device_id: c8ae982a520cbfe26c2754fdbcb8112d
    entity_id: light.bathroom_light
    domain: light
  mode: single
- id: '1619831685297'
  alias: Bathroom shower light timer
  trigger:
  - platform: device
    type: turned_on
    device_id: b9583d307ba0e749fc335f44fb6ffb23
    entity_id: light.bathroom_shower_light_dimmer
    domain: light
    for:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  action:
  - type: turn_off
    device_id: b9583d307ba0e749fc335f44fb6ffb23
    entity_id: light.bathroom_shower_light_dimmer
    domain: light
  mode: single
- id: '1619831641257'
  alias: Bathroom fan timer
  trigger:
  - platform: device
    type: turned_on
    device_id: 8c03fb3350e3fad8e24440cbce7aca0f
    entity_id: switch.bathroom_exhaust_fan
    domain: switch
    for:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  action:
  - type: turn_off
    device_id: 8c03fb3350e3fad8e24440cbce7aca0f
    entity_id: switch.bathroom_exhaust_fan
    domain: switch
  mode: single
- id: '1620189066928'
  alias: Garage door failed to close notification
  description: ''
  trigger:
  - platform: state
    entity_id: cover.garage_door
    from: Closing
    to: Open
  condition: []
  action:
  - service: notify.mobile_app_pixel_3_xl
    data:
      title: Garage door alert
      message: Looks like the garage door failed to close
  mode: single
- id: '1620669762626'
  alias: Guest Bedroom Lamp Switch
  description: Turn on and off lamp with spare light switch
  trigger:
  - type: turned_on
    platform: device
    device_id: 93c6ef95680cc99d052786082d61133e
    entity_id: binary_sensor.guest_bedroom_lamp_switch_button
    domain: binary_sensor
  condition: []
  action:
  - choose:
    - conditions:
      - condition: device
        type: is_off
        device_id: f262375ae55c7c584aaa9d72dffc6fe1
        entity_id: light.guest_bedroom_lamp
        domain: light
      sequence:
      - type: turn_on
        device_id: f262375ae55c7c584aaa9d72dffc6fe1
        entity_id: light.guest_bedroom_lamp
        domain: light
      - type: turn_on
        device_id: 93c6ef95680cc99d052786082d61133e
        entity_id: switch.guest_bedroom_lamp_switch_led
        domain: switch
    - conditions:
      - condition: device
        type: is_on
        device_id: f262375ae55c7c584aaa9d72dffc6fe1
        entity_id: light.guest_bedroom_lamp
        domain: light
      sequence:
      - type: turn_off
        device_id: f262375ae55c7c584aaa9d72dffc6fe1
        entity_id: light.guest_bedroom_lamp
        domain: light
      - type: turn_off
        device_id: 93c6ef95680cc99d052786082d61133e
        entity_id: switch.guest_bedroom_lamp_switch_led
        domain: switch
    default: []
  mode: single
- id: '1620671665827'
  alias: Kitchen task lights button LED off
  description: ''
  trigger:
  - platform: state
    entity_id: group.kitchen_task_lights
    to: 'off'
  condition: []
  action:
  - type: turn_off
    device_id: 4cc524fbec3b232ae9761fbe9a9e9201
    entity_id: switch.kitchen_extra_switch_led
    domain: switch
  mode: single
- id: '1620672171200'
  alias: Kitchen task lights button LED on
  description: ''
  trigger:
  - platform: state
    entity_id: group.kitchen_task_lights
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: 4cc524fbec3b232ae9761fbe9a9e9201
    entity_id: switch.kitchen_extra_switch_led
    domain: switch
  mode: single
