
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    base_url: http://192.168.1.107:8123
# Enables support for tracking state changes over time
history:

recorder:
  purge_keep_days: 4

api:

mqtt:
  birth_message:
    topic: "tele/sirius/hass/LWT"
    payload: "Online"
  will_message:
    topic: "tele/sirius/hass/LWT"
    payload: "Offline"

homeassistant:
  customize: !include customize.yaml

lovelace:
  # mode: yaml

cloud:

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
light: !include_dir_merge_list lights
switch: !include_dir_merge_list switches
fan: !include_dir_merge_list fans
# shell_command: !include shell_commands.yaml
# device_tracker: !include device_tracker.yaml
# notify: !include notify.yaml
# shell_command: !include shell_commands.yaml

wake_on_lan:

webostv:
  host: 192.168.1.234
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "a8:23:fe:06:02:e7"
  customize:
    sources:
      - HDMI 1
      - HDMI 2
      - HDMI 3
      - Chromecast
      - Netflix
      - Amazon Prime Video
      - Hulu
      - Youtube

influxdb:
  host: 192.168.1.107
  port: 8086
  database: hass
  username: homeassistant
  password: homeassistant
  include:
    domains:
      - light
      - fan
      - sensor
      - binary_sensor
      - switch
      - yr
      - sun
      - group
      - device_tracker
      - input_select
      - input_text
      - tplink
      - climate

octoprint:
  host: vulcan.lan
  api_key: E87E789808B4415CA3BD8E34BBDAC4FA
  name: Vulcan
  number_of_tools: 1
  bed: True

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://vulcan.lan/webcam/?action=snapshot
    mjpeg_url: http://vulcan.lan/webcam/?action=stream

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id
