
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate

# Enables support for tracking state changes over time
history:

recorder:
  purge_interval: 1
  purge_keep_days: 4

mqtt:
  broker: 192.168.1.107
  port: 1883
  client_id: homeassistant
  keepalive: 60
  birth_message:
    topic: "tele/sirius/hass/LWT"
    payload: "Online"
  will_message:
    topic: "tele/sirius/hass/LWT"
    payload: "Offline"

homeassistant:
  customize: !include customize.yaml

lovelace:
  mode: yaml

cloud:

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
light: !include_dir_merge_list lights
# switch: !include_dir_merge_list switches
# shell_command: !include shell_commands.yaml
# device_tracker: !include device_tracker.yaml
# notify: !include notify.yaml
# shell_command: !include shell_commands.yaml

tplink: !include tplink.yaml

wake_on_lan:

media_player:
  - platform: webostv
    host: 192.168.1.202
    name: Living Room TV
    filename: webostv.conf
    timeout: 5
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "04:4E:AF:82:03:D8"

influxdb:
  host: 192.168.1.107
  port: 8086
  database: hass
  username: homeassistant
  password: homeassistant
  include:
    domains:
      - light
      - fan
      - sensor
      - binary_sensor
      - switch
      - yr
      - sun
      - group
      - device_tracker
      - input_select
      - input_text
      - tplink
