
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

mqtt:
  broker: 192.168.1.107
  birth_message:
    topic: "tele/sirius/hass/LWT"
    payload: "Online"
  will_message:
    topic: "tele/sirius/hass/LWT"
    payload: "Offline"

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
light: !include_dir_merge_list lights
switch: !include_dir_merge_list switches
fan: !include_dir_merge_list fans

influxdb:
  host: 192.168.1.107
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state

wake_on_lan:

webostv:
  host: 192.168.1.234
  name: Living Room TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: "a8:23:fe:06:02:e7"
  customize:
    sources:
      - HDMI 1
      - HDMI 2
      - HDMI 3
      - Chromecast
      - Netflix
      - Amazon Prime Video
      - Hulu
      - Youtube

octoprint:
  host: 192.168.1.14
  api_key: E87E789808B4415CA3BD8E34BBDAC4FA
  name: Vulcan
  number_of_tools: 1
  bed: True

camera:
  - platform: mjpeg
    name: OctoPrint
    still_image_url: http://vulcan.lan/webcam/?action=snapshot
    mjpeg_url: http://vulcan.lan/webcam/?action=stream

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id