resources:
  - type: js
    url: /local/content-card-example.js
  - url: /local/decluttering-card.js
    type: module

decluttering_templates:
  tasmota_basic:
    card:
      type: picture-elements
      title: '[[title]]'
      image: /local/Blank.jpg
      elements:
        - type: state-label
          entity: 'sensor.[[entity]]_time'
          style:
            left: 10px
            top: 0px
            transform: none
          prefix: 'Last updated: '
        - type: state-label
          entity: 'sensor.[[entity]]_uptime'
          style:
            left: 10px
            top: 24px
            transform: none
          prefix: 'Uptime: '
        - type: state-badge
          entity: 'sensor.[[entity]]_power'
          style:
            right: 0px
            top: -16px
            transform: right
          title: null
        - type: state-label
          entity: 'sensor.[[entity]]_wifi_ssid'
          style:
            left: 10px
            top: 48px
            transform: none
          prefix: 'WiFi: '
        - type: state-label
          entity: 'sensor.[[entity]]_wifi_ap'
          style:
            left: 120px
            top: 48px
            transform: none
        - type: state-label
          entity: 'sensor.[[entity]]_wifi_rssi'
          style:
            text-align: left
            left: 10px
            top: 72px
            transform: none
          prefix: 'RSSI: '
        - type: state-label
          entity: 'sensor.[[entity]]_wifi_channel'
          style:
            left: 120px
            top: 72px
            transform: none
          prefix: 'Channel: '
        - type: state-label
          entity: 'sensor.[[entity]]_wifi_linkcount'
          style:
            text-align: left
            left: 10px
            top: 96px
            transform: none
          prefix: 'Link count: '
        - type: state-label
          entity: 'sensor.[[entity]]_wifi_downtime'
          style:
            left: 120px
            top: 96px
            transform: none
          prefix: 'Downtime: '
        - type: state-label
          entity: 'sensor.[[entity]]_vcc'
          style:
            text-align: left
            left: 10px
            top: 120px
            transform: none
          prefix: 'VCC: '
        - type: state-label
          entity: 'sensor.[[entity]]_loadavg'
          style:
            left: 120px
            top: 120px
            transform: none
          prefix: 'Load Avg: '

title: Home
views:
  - title: Home
    badges:
      - sensor.current_energy_usage
    cards:
      - type: media-control
        entity: media_player.living_room_tv
      - entities:
          - entity: light.living_room_lights
          - entity: light.living_room_lamp
            name: Lamp
            icon: mdi:floor-lamp
          - entity: group.living_room_accent_lamps
        show_header_toggle: true
        theme: Backend-selected
        title: Living Room
        type: entities
      - entities:
          - entity: light.kitchen_ceiling_lights
            name: Ceiling Lights
          - entity: light.kitchen_sink_light
            name: Sink Light
          - entity: switch.kitchen_undercabinet_lights
            name: Undercabinet Lights
            icon: mdi:lightbulb
          - entity: switch.dining_room_light
            icon: mdi:lightbulb
          - entity: switch.pantry_light
            icon: mdi:lightbulb
          - entity: group.kitchen_cabinet_accent_lights
        title: Kitchen
        type: entities
      - entities:
          - entity: switch.master_bedroom_lights
            name: Bedroom Lights
            icon: mdi:lightbulb
          - entity: switch.master_bedroom_fan
            name: Bedroom Fan
          - entity: switch.master_closet_lights
            name: Closet Lights
          - entity: switch.master_bathroom_lights
            name: Bathroom Lights
            icon: mdi:lightbulb
          - entity: light.master_bathroom_shower_light
            name: Shower Light
          - entity: switch.master_bathroom_fan
            name: Bathroom Fan
            icon: mdi:fan
        title: Master Suite
        type: entities
      - entities:
          - entity: switch.foyer_light
            icon: mdi:lightbulb
          - entity: switch.laundry_room_light
            icon: mdi:lightbulb
          - entity: switch.mud_room_light
            icon: mdi:lightbulb
          - entity: switch.dog_room_lights
            icon: mdi:lightbulb
          - entity: switch.downstairs_hall_light
            icon: mdi:lightbulb
          - entity: switch.upstairs_hall_light
            icon: mdi:lightbulb
        title: Hall
        type: entities
      - entities:
          - entity: switch.office_lights
            icon: mdi:lightbulb
        title: Office
        type: entities
      - entities:
          - entity: switch.powder_room_light
            name: Light
            icon: mdi:lightbulb
          - entity: switch.powder_room_fan
            name: Fan
            icon: mdi:fan
        title: Powder Room
        type: entities
      - entities:
          - entity: switch.dance_studio_light
            name: Light
            icon: mdi:lightbulb
        title: Dance Studio
        type: entities
      - entities:
          - entity: switch.workout_room_light
            name: Light
            icon: mdi:lightbulb
          - entity: switch.workout_room_fan
            name: Fan
            icon: mdi:fan
        title: Workout Room
        type: entities
      - entities:
          - entity: switch.guest_bedroom_light
            name: Light
            icon: mdi:lightbulb
        title: Guest Bedroom
        type: entities
      - entities:
          - entity: switch.basement_stairs_lights
            icon: mdi:lightbulb
          - entity: switch.basement_lights
            icon: mdi:lightbulb
        title: Basement
        type: entities
      - entities:
          - entity: switch.front_porch_light
            icon: mdi:lightbulb
          - entity: switch.driveway_lights
            icon: mdi:lightbulb
          - entity: switch.garage_lights
            icon: mdi:lightbulb
        title: Outside
        type: entities
    path: default_view
  - title: Settings
    icon: 'mdi:settings'
    cards:
      - type: entity-button
        name: Bedtime - Turn everything off
        icon: mdi:hotel
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.bedtime
        entity: script.bedtime
      - type: entities
        title: Google Wifi
        show_header_toggle: false
        show_icon: true
        show_name: true
        show_state: true
        entities:
          - entity: sensor.google_wifi_uptime
          - entity: sensor.google_wifi_status
          - entity: sensor.google_wifi_current_version
          - entity: sensor.google_wifi_new_version
          - entity: sensor.google_wifi_last_restart
          - entity: sensor.google_wifi_local_ip
      - type: vertical-stack
        cards:
          - type: glance
            title: Living Room Accent Lamp  01
            show_icon: false
            show_name: true
            show_state: true
            entities:
              - entity: sensor.living_room_accent_lamp_01_power
              - entity: sensor.living_room_accent_lamp_01_uptime
              - entity: sensor.living_room_accent_lamp_01_color
              - entity: sensor.living_room_accent_lamp_01_color_channel
              - entity: sensor.living_room_accent_lamp_01_hsb_color
              - entity: sensor.living_room_accent_lamp_01_dimmer
              - entity: sensor.living_room_accent_lamp_01_fade
              - entity: sensor.living_room_accent_lamp_01_led_table
              - entity: sensor.living_room_accent_lamp_01_speed
              - entity: sensor.living_room_accent_lamp_01_scheme
              - entity: sensor.living_room_accent_lamp_01_loadavg
              - entity: sensor.living_room_accent_lamp_01_heap
              - entity: sensor.living_room_accent_lamp_01_sleep
              - entity: sensor.living_room_accent_lamp_01_sleepmode
              - entity: sensor.living_room_accent_lamp_01_time
              - entity: sensor.living_room_accent_lamp_01_vcc
              - entity: sensor.living_room_accent_lamp_01_wifi_ap
              - entity: sensor.living_room_accent_lamp_01_wifi_bssid
              - entity: sensor.living_room_accent_lamp_01_wifi_channel
              - entity: sensor.living_room_accent_lamp_01_wifi_downtime
              - entity: sensor.living_room_accent_lamp_01_wifi_linkcount
              - entity: sensor.living_room_accent_lamp_01_wifi_rssi
              - entity: sensor.living_room_accent_lamp_01_wifi_ssid

          - type: glance
            title: Living Room Accent Lamp  02
            show_icon: false
            show_name: true
            show_state: true
            entities:
              - entity: sensor.living_room_accent_lamp_02_power
              - entity: sensor.living_room_accent_lamp_02_uptime
              - entity: sensor.living_room_accent_lamp_02_color
              - entity: sensor.living_room_accent_lamp_02_color_channel
              - entity: sensor.living_room_accent_lamp_02_hsb_color
              - entity: sensor.living_room_accent_lamp_02_dimmer
              - entity: sensor.living_room_accent_lamp_02_fade
              - entity: sensor.living_room_accent_lamp_02_led_table
              - entity: sensor.living_room_accent_lamp_02_speed
              - entity: sensor.living_room_accent_lamp_02_scheme
              - entity: sensor.living_room_accent_lamp_02_loadavg
              - entity: sensor.living_room_accent_lamp_02_heap
              - entity: sensor.living_room_accent_lamp_02_sleep
              - entity: sensor.living_room_accent_lamp_02_sleepmode
              - entity: sensor.living_room_accent_lamp_02_time
              - entity: sensor.living_room_accent_lamp_02_vcc
              - entity: sensor.living_room_accent_lamp_02_wifi_ap
              - entity: sensor.living_room_accent_lamp_02_wifi_bssid
              - entity: sensor.living_room_accent_lamp_02_wifi_channel
              - entity: sensor.living_room_accent_lamp_02_wifi_downtime
              - entity: sensor.living_room_accent_lamp_02_wifi_linkcount
              - entity: sensor.living_room_accent_lamp_02_wifi_rssi
              - entity: sensor.living_room_accent_lamp_02_wifi_ssid
      - type: vertical-stack
        cards:
          - type: glance
            title: Kitchen Cabinet Accent RGB 01
            show_icon: false
            show_name: true
            show_state: true
            entities:
              - entity: sensor.kitchen_cabinet_accent_rgb_01_power
              - entity: sensor.kitchen_cabinet_accent_rgb_01_uptime
              - entity: sensor.kitchen_cabinet_accent_rgb_01_color
              - entity: sensor.kitchen_cabinet_accent_rgb_01_color_channel
              - entity: sensor.kitchen_cabinet_accent_rgb_01_hsb_color
              - entity: sensor.kitchen_cabinet_accent_rgb_01_dimmer
              - entity: sensor.kitchen_cabinet_accent_rgb_01_fade
              - entity: sensor.kitchen_cabinet_accent_rgb_01_led_table
              - entity: sensor.kitchen_cabinet_accent_rgb_01_speed
              - entity: sensor.kitchen_cabinet_accent_rgb_01_scheme
              - entity: sensor.kitchen_cabinet_accent_rgb_01_loadavg
              - entity: sensor.kitchen_cabinet_accent_rgb_01_heap
              - entity: sensor.kitchen_cabinet_accent_rgb_01_sleep
              - entity: sensor.kitchen_cabinet_accent_rgb_01_sleepmode
              - entity: sensor.kitchen_cabinet_accent_rgb_01_time
              - entity: sensor.kitchen_cabinet_accent_rgb_01_vcc
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_ap
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_bssid
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_channel
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_downtime
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_linkcount
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_rssi
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_ssid
          - type: glance
            title: Kitchen Cabinet Accent RGB 02
            show_icon: false
            show_name: true
            show_state: true
            entities:
              - entity: sensor.kitchen_cabinet_accent_rgb_02_power
              - entity: sensor.kitchen_cabinet_accent_rgb_02_uptime
              - entity: sensor.kitchen_cabinet_accent_rgb_02_color
              - entity: sensor.kitchen_cabinet_accent_rgb_02_color_channel
              - entity: sensor.kitchen_cabinet_accent_rgb_02_hsb_color
              - entity: sensor.kitchen_cabinet_accent_rgb_02_dimmer
              - entity: sensor.kitchen_cabinet_accent_rgb_02_fade
              - entity: sensor.kitchen_cabinet_accent_rgb_02_led_table
              - entity: sensor.kitchen_cabinet_accent_rgb_02_speed
              - entity: sensor.kitchen_cabinet_accent_rgb_02_scheme
              - entity: sensor.kitchen_cabinet_accent_rgb_02_loadavg
              - entity: sensor.kitchen_cabinet_accent_rgb_02_heap
              - entity: sensor.kitchen_cabinet_accent_rgb_02_sleep
              - entity: sensor.kitchen_cabinet_accent_rgb_02_sleepmode
              - entity: sensor.kitchen_cabinet_accent_rgb_02_time
              - entity: sensor.kitchen_cabinet_accent_rgb_02_vcc
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_ap
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_bssid
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_channel
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_downtime
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_linkcount
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_rssi
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_ssid
      - type: glance
        title: Living Room Lamp
        show_icon: false
        show_name: true
        show_state: true
        entities:
          - entity: sensor.living_room_lamp_power
          - entity: sensor.living_room_lamp_time
          - entity: sensor.living_room_lamp_uptime
          - entity: sensor.living_room_lamp_vcc
          - entity: sensor.living_room_lamp_heap
          - entity: sensor.living_room_lamp_sleepmode
          - entity: sensor.living_room_lamp_sleep
          - entity: sensor.living_room_lamp_loadavg
          - entity: sensor.living_room_lamp_wifi_ssid
          - entity: sensor.living_room_lamp_wifi_ap
          - entity: sensor.living_room_lamp_wifi_bssid
          - entity: sensor.living_room_lamp_wifi_channel
          - entity: sensor.living_room_lamp_wifi_rssi
          - entity: sensor.living_room_lamp_wifi_linkcount
          - entity: sensor.living_room_lamp_wifi_downtime
  - title: Test
    cards:
      - type: custom:decluttering-card
        template: tasmota_basic
        variables:
          - title: Living Room Lamp
          - entity: living_room_lamp
      - type: custom:decluttering-card
        template: tasmota_basic
        variables:
          - title: Living Room Accent Lamp 01
          - entity: living_room_accent_lamp_01
      - type: custom:decluttering-card
        template: tasmota_basic
        variables:
          - title: Living Room Accent Lamp 02
          - entity: living_room_accent_lamp_02
      - type: custom:decluttering-card
        template: tasmota_basic
        variables:
          - title: Kitchen Cabinet Accent 01
          - entity: kitchen_cabinet_accent_rgb_01
      - type: custom:decluttering-card
        template: tasmota_basic
        variables:
          - title: Kitchen Cabinet Accent 02
          - entity: kitchen_cabinet_accent_rgb_02
