resources:
  - type: js
    url: /local/content-card-example.js
title: Home
views:
  - title: Home
    badges:
      - person.mike_fink
      - sun.sun
    cards:
      - type: media-control
        entity: media_player.living_room_tv
      - entities:
          - entity: light.living_room_lights
          - entity: light.living_room_lamp
          - entity: group.living_room_accent_lamps
        show_header_toggle: true
        theme: Backend-selected
        title: Living Room
        type: entities
      - entities:
          - entity: switch.kitchen_lights
          - entity: switch.kitchen_sink_light
          - entity: switch.kitchen_undercabinet_lights
          - entity: switch.dining_room_light
          - entity: switch.pantry_light
          - entity: group.kitchen_cabinet_accent_lights
        title: Kitchen
        type: entities
      - entities:
          - entity: switch.master_bedroom_lights
          - entity: switch.master_bedroom_fan
          - entity: switch.master_closet_lights
          - entity: switch.master_bathroom_lights
          - entity: switch.master_bathroom_shower_light
          - entity: switch.master_bathroom_fan
        title: Master Suite
        type: entities
      - entities:
          - entity: switch.foyer_light
          - entity: switch.mud_room_light
          - entity: switch.dog_room_lights
          - entity: switch.downstairs_hall_light
          - entity: switch.upstairs_hall_light
        title: Hall
        type: entities
      - entities:
          - entity: switch.powder_room_light
          - entity: switch.powder_room_fan
        title: Powder Room
        type: entities
      - entities:
          - entity: switch.front_porch_light
        title: Outside
        type: entities
    path: default_view
  - title: Settings
    icon: 'mdi:settings'
    cards:
      - type: entity-button
        name: Bedtime - Turn everything off
        icon: mdi:hotel
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.bedtime
        entity: script.bedtime
      - type: entities
        title: Google Wifi
        show_header_toggle: false
        show_icon: true
        show_name: true
        show_state: true
        entities:
          - entity: sensor.google_wifi_uptime
          - entity: sensor.google_wifi_status
          - entity: sensor.google_wifi_current_version
          - entity: sensor.google_wifi_new_version
          - entity: sensor.google_wifi_last_restart
          - entity: sensor.google_wifi_local_ip
      - type: vertical-stack
        cards:
          - type: glance
            title: Living Room Accent Lamp  01
            show_icon: false
            show_name: true
            show_state: true
            entities:
              - entity: sensor.living_room_accent_lamp_01_power
              - entity: sensor.living_room_accent_lamp_01_uptime
              - entity: sensor.living_room_accent_lamp_01_color
              - entity: sensor.living_room_accent_lamp_01_color_channel
              - entity: sensor.living_room_accent_lamp_01_hsb_color
              - entity: sensor.living_room_accent_lamp_01_dimmer
              - entity: sensor.living_room_accent_lamp_01_fade
              - entity: sensor.living_room_accent_lamp_01_led_table
              - entity: sensor.living_room_accent_lamp_01_speed
              - entity: sensor.living_room_accent_lamp_01_scheme
              - entity: sensor.living_room_accent_lamp_01_loadavg
              - entity: sensor.living_room_accent_lamp_01_heap
              - entity: sensor.living_room_accent_lamp_01_sleep
              - entity: sensor.living_room_accent_lamp_01_sleepmode
              - entity: sensor.living_room_accent_lamp_01_time
              - entity: sensor.living_room_accent_lamp_01_vcc
              - entity: sensor.living_room_accent_lamp_01_wifi_ap
              - entity: sensor.living_room_accent_lamp_01_wifi_bssid
              - entity: sensor.living_room_accent_lamp_01_wifi_channel
              - entity: sensor.living_room_accent_lamp_01_wifi_downtime
              - entity: sensor.living_room_accent_lamp_01_wifi_linkcount
              - entity: sensor.living_room_accent_lamp_01_wifi_rssi
              - entity: sensor.living_room_accent_lamp_01_wifi_ssid

          - type: glance
            title: Living Room Accent Lamp  02
            show_icon: false
            show_name: true
            show_state: true
            entities:
              - entity: sensor.living_room_accent_lamp_02_power
              - entity: sensor.living_room_accent_lamp_02_uptime
              - entity: sensor.living_room_accent_lamp_02_color
              - entity: sensor.living_room_accent_lamp_02_color_channel
              - entity: sensor.living_room_accent_lamp_02_hsb_color
              - entity: sensor.living_room_accent_lamp_02_dimmer
              - entity: sensor.living_room_accent_lamp_02_fade
              - entity: sensor.living_room_accent_lamp_02_led_table
              - entity: sensor.living_room_accent_lamp_02_speed
              - entity: sensor.living_room_accent_lamp_02_scheme
              - entity: sensor.living_room_accent_lamp_02_loadavg
              - entity: sensor.living_room_accent_lamp_02_heap
              - entity: sensor.living_room_accent_lamp_02_sleep
              - entity: sensor.living_room_accent_lamp_02_sleepmode
              - entity: sensor.living_room_accent_lamp_02_time
              - entity: sensor.living_room_accent_lamp_02_vcc
              - entity: sensor.living_room_accent_lamp_02_wifi_ap
              - entity: sensor.living_room_accent_lamp_02_wifi_bssid
              - entity: sensor.living_room_accent_lamp_02_wifi_channel
              - entity: sensor.living_room_accent_lamp_02_wifi_downtime
              - entity: sensor.living_room_accent_lamp_02_wifi_linkcount
              - entity: sensor.living_room_accent_lamp_02_wifi_rssi
              - entity: sensor.living_room_accent_lamp_02_wifi_ssid
      - type: vertical-stack
        cards:
          - type: glance
            title: Kitchen Cabinet Accent RGB 01
            show_icon: false
            show_name: true
            show_state: true
            entities:
              - entity: sensor.kitchen_cabinet_accent_rgb_01_power
              - entity: sensor.kitchen_cabinet_accent_rgb_01_uptime
              - entity: sensor.kitchen_cabinet_accent_rgb_01_color
              - entity: sensor.kitchen_cabinet_accent_rgb_01_color_channel
              - entity: sensor.kitchen_cabinet_accent_rgb_01_hsb_color
              - entity: sensor.kitchen_cabinet_accent_rgb_01_dimmer
              - entity: sensor.kitchen_cabinet_accent_rgb_01_fade
              - entity: sensor.kitchen_cabinet_accent_rgb_01_led_table
              - entity: sensor.kitchen_cabinet_accent_rgb_01_speed
              - entity: sensor.kitchen_cabinet_accent_rgb_01_scheme
              - entity: sensor.kitchen_cabinet_accent_rgb_01_loadavg
              - entity: sensor.kitchen_cabinet_accent_rgb_01_heap
              - entity: sensor.kitchen_cabinet_accent_rgb_01_sleep
              - entity: sensor.kitchen_cabinet_accent_rgb_01_sleepmode
              - entity: sensor.kitchen_cabinet_accent_rgb_01_time
              - entity: sensor.kitchen_cabinet_accent_rgb_01_vcc
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_ap
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_bssid
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_channel
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_downtime
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_linkcount
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_rssi
              - entity: sensor.kitchen_cabinet_accent_rgb_01_wifi_ssid
          - type: glance
            title: Kitchen Cabinet Accent RGB 02
            show_icon: false
            show_name: true
            show_state: true
            entities:
              - entity: sensor.kitchen_cabinet_accent_rgb_02_power
              - entity: sensor.kitchen_cabinet_accent_rgb_02_uptime
              - entity: sensor.kitchen_cabinet_accent_rgb_02_color
              - entity: sensor.kitchen_cabinet_accent_rgb_02_color_channel
              - entity: sensor.kitchen_cabinet_accent_rgb_02_hsb_color
              - entity: sensor.kitchen_cabinet_accent_rgb_02_dimmer
              - entity: sensor.kitchen_cabinet_accent_rgb_02_fade
              - entity: sensor.kitchen_cabinet_accent_rgb_02_led_table
              - entity: sensor.kitchen_cabinet_accent_rgb_02_speed
              - entity: sensor.kitchen_cabinet_accent_rgb_02_scheme
              - entity: sensor.kitchen_cabinet_accent_rgb_02_loadavg
              - entity: sensor.kitchen_cabinet_accent_rgb_02_heap
              - entity: sensor.kitchen_cabinet_accent_rgb_02_sleep
              - entity: sensor.kitchen_cabinet_accent_rgb_02_sleepmode
              - entity: sensor.kitchen_cabinet_accent_rgb_02_time
              - entity: sensor.kitchen_cabinet_accent_rgb_02_vcc
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_ap
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_bssid
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_channel
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_downtime
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_linkcount
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_rssi
              - entity: sensor.kitchen_cabinet_accent_rgb_02_wifi_ssid
      - type: glance
        title: Living Room Lamp
        show_icon: false
        show_name: true
        show_state: true
        entities:
          - entity: sensor.living_room_lamp_power
          - entity: sensor.living_room_lamp_time
          - entity: sensor.living_room_lamp_uptime
          - entity: sensor.living_room_lamp_vcc
          - entity: sensor.living_room_lamp_heap
          - entity: sensor.living_room_lamp_sleepmode
          - entity: sensor.living_room_lamp_sleep
          - entity: sensor.living_room_lamp_loadavg
          - entity: sensor.living_room_lamp_wifi_ssid
          - entity: sensor.living_room_lamp_wifi_ap
          - entity: sensor.living_room_lamp_wifi_bssid
          - entity: sensor.living_room_lamp_wifi_channel
          - entity: sensor.living_room_lamp_wifi_rssi
          - entity: sensor.living_room_lamp_wifi_linkcount
          - entity: sensor.living_room_lamp_wifi_downtime