- platform: mqtt
  name: 'Foyer Downstairs Lightswitch'
  state_topic: 'stat/foyer/downstairs-lightswitch/POWER1'
  command_topic: 'cmnd/foyer/downstairs-lightswitch/EVENT'
  json_attributes_topic: 'tele/foyer/downstairs-lightswitch/STATE'
  availability_topic: 'tele/foyer/downstairs-lightswitch/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
  payload_on: 'ON'
  payload_off: 'OFF'
