# This template light entity fixes an issue with the ESPHome dimmer.
# ESPHome is configured with min/max dimmer values of 15%/100%.
# The Home Assistant UI correspondingly gives you a dimmer that can't
# be set blelow 15%. If you select < 15%, the slider jumps back up to 15%.
# Usable, but not ideal. Since Home Assistant uses 0-255 for brightness, 
# we need to map {38.25:255} to {0:255} when sending brightness commands to
# the light. And then we need to map in the other direction when reading the
# brightness reported by the light. Except a brightness of 0, to Home
# Assistant, means Off (which it doesn't know how to interpret when it also
# sees that the light is On), so the if/else in level_template fixes this.
#
# See '../esphome/Kitchen Under Cabinet Dimmer Switch.yaml' for the ESPHome config

- platform: template
  lights:
    kitchen_under_cabinet_lights_dimmer_ui:
      friendly_name: "Kitchen Under Cabinet Lights"
      level_template: >
        {% if state_attr('light.kitchen_under_cabinet_lights_dimmer', 'brightness') <= 39 %}
        1
        {% else %}
        {{ 1.17647 * (state_attr('light.kitchen_under_cabinet_lights_dimmer', 'brightness') | float - 38.25) | int }}
        {% endif %}
      value_template: "{{states('light.kitchen_under_cabinet_lights_dimmer')}}"
      turn_on:
        service: light.turn_on
        entity_id: light.kitchen_under_cabinet_lights_dimmer
      turn_off:
        service: light.turn_off
        entity_id: light.kitchen_under_cabinet_lights_dimmer
      set_level:
        service: light.turn_on
        data_template:
          entity_id: light.kitchen_under_cabinet_lights_dimmer
          brightness: "{{ ( 0.85 * brightness | float + 38.25 ) | int }}"
