- platform: mqtt
  name: Living Room Accent Lamp 01
  effect_list:
    - 2
    - 3
  state_topic: "stat/1167boyd/living-room/accent-lamp-01/RESULT"
  command_topic: "cmnd/1167boyd/living-room/accent-lamp-01/POWER"
  availability_topic: "tele/1167boyd/living-room/accent-lamp-01/LWT"
  brightness_state_topic: "stat/1167boyd/living-room/accent-lamp-01/RESULT"
  brightness_command_topic: "cmnd/1167boyd/living-room/accent-lamp-01/Dimmer"
  brightness_scale: 100
  rgb_command_template: "{{ '%02x%02x%02x00' | format(green, red, blue)}}"
  rgb_state_topic: "stat/1167boyd/living-room/accent-lamp-01/RESULT"
  rgb_command_topic: "cmnd/1167boyd/living-room/accent-lamp-01/Color"
  #white_command_template:
  white_value_state_topic: "stat/1167boyd/living-room/accent-lamp-01/RESULT"
  white_value_command_topic: "cmnd/1167boyd/living-room/accent-lamp-01/channel4"
  white_value_scale: 100
  effect_command_topic: "cmnd/1167boyd/living-room/accent-lamp-01/Scheme"
  effect_state_topic: "stat/1167boyd/living-room/accent-lamp-01/RESULT"
  state_value_template: >
    {% if "POWER" in value_json %}
      {{ value_json.POWER }}
    {% endif %}
  brightness_value_template: >
    {% if "Dimmer" in value_json %}
      {{ value_json.Dimmer }}
    {% endif %}
  effect_value_template: >
    {% if "Scheme" in value_json %}
      {{ value_json.Scheme }}
    {% endif %}
  rgb_value_template: >
    {% if "Color" in value_json %}
      {{ (value_json.Color[2:4] | int(int, 16)) | string + ',' + (value_json.Color[0:2] | int(int, 16)) | string + ',' + (value_json.Color[4:6] | int(int, 16)) | string }}
    {% endif %}
  white_value_template: >
    {% if "Channel4" in value_json %}
      {{ value_json.Channel4}}
    {% endif %}
  payload_on: "ON"
  payload_off: "OFF"
  on_command_type: "brightness"
  payload_available: "Online"
  payload_not_available: "Offline"
  json_attributes_topic: "tele/1167boyd/living-room/accent-lamp-01/STATE"

- platform: mqtt
  name: Living Room Accent Lamp 02
  effect_list:
    - 2
    - 3
  state_topic: "stat/1167boyd/living-room/accent-lamp-02/RESULT"
  command_topic: "cmnd/1167boyd/living-room/accent-lamp-02/POWER"
  availability_topic: "tele/1167boyd/living-room/accent-lamp-02/LWT"
  brightness_state_topic: "stat/1167boyd/living-room/accent-lamp-02/RESULT"
  brightness_command_topic: "cmnd/1167boyd/living-room/accent-lamp-02/Dimmer"
  brightness_scale: 100
  rgb_command_template: "{{ '%02x%02x%02x00' | format(green, red, blue)}}"
  rgb_state_topic: "stat/1167boyd/living-room/accent-lamp-02/RESULT"
  rgb_command_topic: "cmnd/1167boyd/living-room/accent-lamp-02/Color"
  white_value_state_topic: "stat/1167boyd/living-room/accent-lamp-02/RESULT"
  white_value_command_topic: "cmnd/1167boyd/living-room/accent-lamp-02/channel4"
  white_value_scale: 100
  effect_command_topic: "cmnd/1167boyd/living-room/accent-lamp-02/Scheme"
  effect_state_topic: "stat/1167boyd/living-room/accent-lamp-02/RESULT"
  state_value_template: >
    {% if "POWER" in value_json %}
      {{ value_json.POWER }}
    {% endif %}
  brightness_value_template: >
    {% if "Dimmer" in value_json %}
      {{ value_json.Dimmer }}
    {% endif %}
  effect_value_template: >
    {% if "Scheme" in value_json %}
      {{ value_json.Scheme }}
    {% endif %}
  rgb_value_template: >
    {% if "Color" in value_json %}
      {{ (value_json.Color[2:4] | int(int, 16)) | string + ',' + (value_json.Color[0:2] | int(int, 16)) | string + ',' + (value_json.Color[4:6] | int(int, 16)) | string }}
    {% endif %}
  white_value_template: >
    {% if "Channel4" in value_json %}
      {{ value_json.Channel4}}
    {% endif %}
  payload_on: "ON"
  payload_off: "OFF"
  on_command_type: "brightness"
  payload_available: "Online"
  payload_not_available: "Offline"
  json_attributes_topic: "tele/1167boyd/living-room/accent-lamp-02/STATE"
