- platform: template
  sensors:
    dryer_running:
      friendly_name: "Dryer Running"
      value_template: >-
        {% if states('sensor.dryer_power') | float >= 50.0 %}
          On
        {% else %}
          Off
        {% endif %}
