- platform: template
  sensors:
    kitchen_cabinet_accent_rgb_01_time:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Time'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.Time }}'
    kitchen_cabinet_accent_rgb_01_uptime:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Uptime'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.Uptime }}'
    kitchen_cabinet_accent_rgb_01_vcc:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.Vcc }}'
    kitchen_cabinet_accent_rgb_01_heap:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Heap'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.Heap }}'
    kitchen_cabinet_accent_rgb_01_sleepmode:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 SleepMode'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.SleepMode }}'
    kitchen_cabinet_accent_rgb_01_sleep:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Sleep'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.Sleep }}'
    kitchen_cabinet_accent_rgb_01_loadavg:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.LoadAvg }}'
    kitchen_cabinet_accent_rgb_01_power:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Power'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.POWER }}'
    kitchen_cabinet_accent_rgb_01_dimmer:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Dimmer'
      unit_of_measurement: '%'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.Dimmer }}'
    kitchen_cabinet_accent_rgb_01_color:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Color'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.Color }}'
    kitchen_cabinet_accent_rgb_01_hsb_color:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 HSB Color'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.HSBColor }}'
    kitchen_cabinet_accent_rgb_01_color_channel:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Color Channel'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.Channel }}'
    kitchen_cabinet_accent_rgb_01_scheme:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Scheme'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.Scheme }}'
    kitchen_cabinet_accent_rgb_01_fade:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Fade'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.Fade }}'
    kitchen_cabinet_accent_rgb_01_speed:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Speed'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.Speed }}'
    kitchen_cabinet_accent_rgb_01_led_table:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 LED Table'
      value_template: '{{ states.light.kitchen_cabinet_accent_rgb_01.attributes.LedTable }}'
    kitchen_cabinet_accent_rgb_01_wifi_ssid:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Wifi SSId'
      value_template: "{{ state_attr('light.kitchen_cabinet_accent_rgb_01', 'Wifi')['SSId'] }}"
    kitchen_cabinet_accent_rgb_01_wifi_ap:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Wifi AP'
      value_template: >-
        {% if state_attr('light.kitchen_cabinet_accent_rgb_01', 'Wifi')['BSSId'] | string == '30:FD:38:D3:F6:73' %}
          Kitchen AP
        {% elif state_attr('light.kitchen_cabinet_accent_rgb_01', 'Wifi')['BSSId'] | string == '30:FD:38:D3:FB:6F' %}
          Office AP
        {% elif state_attr('light.kitchen_cabinet_accent_rgb_01', 'Wifi')['BSSId'] | string == '30:FD:38:D3:FB:01' %}
          Workout AP
        {% else %}
          {{ state_attr('light.kitchen_cabinet_accent_rgb_01', 'Wifi')['BSSId'] }}
        {% endif %}
    kitchen_cabinet_accent_rgb_01_wifi_bssid:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Wifi BSSId'
      value_template: "{{ state_attr('light.kitchen_cabinet_accent_rgb_01', 'Wifi')['BSSId'] }}"
    kitchen_cabinet_accent_rgb_01_wifi_channel:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Wifi Channel'
      value_template: "{{ state_attr('light.kitchen_cabinet_accent_rgb_01', 'Wifi')['Channel'] }}"
    kitchen_cabinet_accent_rgb_01_wifi_rssi:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.kitchen_cabinet_accent_rgb_01', 'Wifi')['RSSI'] }}"
    kitchen_cabinet_accent_rgb_01_wifi_linkcount:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Wifi Link Count'
      value_template: "{{ state_attr('light.kitchen_cabinet_accent_rgb_01', 'Wifi')['LinkCount'] }}"
    kitchen_cabinet_accent_rgb_01_wifi_downtime:
      friendly_name: 'Kitchen Cabinet Accent RGB 01 Wifi Downtime'
      value_template: "{{ state_attr('light.kitchen_cabinet_accent_rgb_01', 'Wifi')['Downtime'] }}"
