- platform: template
  sensors:
    living_room_accent_lamp_01_time:
      friendly_name: 'Living Room Accent Lamp 01 Time'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.Time }}'
    living_room_accent_lamp_01_uptime:
      friendly_name: 'Living Room Accent Lamp 01 Uptime'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.Uptime }}'
    living_room_accent_lamp_01_vcc:
      friendly_name: 'Living Room Accent Lamp 01 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.Vcc }}'
    living_room_accent_lamp_01_heap:
      friendly_name: 'Living Room Accent Lamp 01 Heap'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.Heap }}'
    living_room_accent_lamp_01_sleepmode:
      friendly_name: 'Living Room Accent Lamp 01 SleepMode'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.SleepMode }}'
    living_room_accent_lamp_01_sleep:
      friendly_name: 'Living Room Accent Lamp 01 Sleep'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.Sleep }}'
    living_room_accent_lamp_01_loadavg:
      friendly_name: 'Living Room Accent Lamp 01 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.LoadAvg }}'
    living_room_accent_lamp_01_power:
      friendly_name: 'Living Room Accent Lamp 01 Power'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.POWER }}'
    living_room_accent_lamp_01_dimmer:
      friendly_name: 'Living Room Accent Lamp 01 Dimmer'
      unit_of_measurement: '%'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.Dimmer }}'
    living_room_accent_lamp_01_color:
      friendly_name: 'Living Room Accent Lamp 01 Color'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.Color }}'
    living_room_accent_lamp_01_hsb_color:
      friendly_name: 'Living Room Accent Lamp 01 HSB Color'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.HSBColor }}'
    living_room_accent_lamp_01_color_channel:
      friendly_name: 'Living Room Accent Lamp 01 Color Channel'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.Channel }}'
    living_room_accent_lamp_01_scheme:
      friendly_name: 'Living Room Accent Lamp 01 Scheme'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.Scheme }}'
    living_room_accent_lamp_01_fade:
      friendly_name: 'Living Room Accent Lamp 01 Fade'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.Fade }}'
    living_room_accent_lamp_01_speed:
      friendly_name: 'Living Room Accent Lamp 01 Speed'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.Speed }}'
    living_room_accent_lamp_01_led_table:
      friendly_name: 'Living Room Accent Lamp 01 LED Table'
      value_template: '{{ states.light.living_room_accent_lamp_01.attributes.LedTable }}'
    living_room_accent_lamp_01_wifi_ssid:
      friendly_name: 'Living Room Accent Lamp 01 Wifi SSId'
      value_template: "{{ state_attr('light.living_room_accent_lamp_01', 'Wifi')['SSId'] }}"
    living_room_accent_lamp_01_wifi_ap:
      friendly_name: 'Living Room Accent Lamp 01 Wifi AP'
      value_template: >-
        {% if state_attr('light.living_room_accent_lamp_01', 'Wifi')['BSSId'] | string == '30:FD:38:D3:F6:73' %}
          Kitchen AP
        {% elif state_attr('light.living_room_accent_lamp_01', 'Wifi')['BSSId'] | string == '30:FD:38:D3:FB:6F' %}
          Office AP
        {% elif state_attr('light.living_room_accent_lamp_01', 'Wifi')['BSSId'] | string == '30:FD:38:D3:FB:01' %}
          Workout AP
        {% else %}
          {{ state_attr('light.living_room_accent_lamp_01', 'Wifi')['BSSId'] }}
        {% endif %}
    living_room_accent_lamp_01_wifi_bssid:
      friendly_name: 'Living Room Accent Lamp 01 Wifi AP'
      value_template: "{{ state_attr('light.living_room_accent_lamp_01', 'Wifi')['BSSId'] }}"
    living_room_accent_lamp_01_wifi_channel:
      friendly_name: 'Living Room Accent Lamp 01 Wifi Channel'
      value_template: "{{ state_attr('light.living_room_accent_lamp_01', 'Wifi')['Channel'] }}"
    living_room_accent_lamp_01_wifi_rssi:
      friendly_name: 'Living Room Accent Lamp 01 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.living_room_accent_lamp_01', 'Wifi')['RSSI'] }}"
    living_room_accent_lamp_01_wifi_linkcount:
      friendly_name: 'Living Room Accent Lamp 01 Wifi Link Count'
      value_template: "{{ state_attr('light.living_room_accent_lamp_01', 'Wifi')['LinkCount'] }}"
    living_room_accent_lamp_01_wifi_downtime:
      friendly_name: 'Living Room Accent Lamp 01 Wifi Downtime'
      value_template: "{{ state_attr('light.living_room_accent_lamp_01', 'Wifi')['Downtime'] }}"
