- platform: template
  sensors:
    living_room_accent_lamp_02_time:
      friendly_name: 'Living Room Accent Lamp 02 Time'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Time }}'
    living_room_accent_lamp_02_uptime:
      friendly_name: 'Living Room Accent Lamp 02 Uptime'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Uptime }}'
    living_room_accent_lamp_02_vcc:
      friendly_name: 'Living Room Accent Lamp 02 Vcc'
      unit_of_measurement: 'V'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Vcc }}'
    living_room_accent_lamp_02_heap:
      friendly_name: 'Living Room Accent Lamp 02 Heap'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Heap }}'
    living_room_accent_lamp_02_sleepmode:
      friendly_name: 'Living Room Accent Lamp 02 SleepMode'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.SleepMode }}'
    living_room_accent_lamp_02_sleep:
      friendly_name: 'Living Room Accent Lamp 02 Sleep'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Sleep }}'
    living_room_accent_lamp_02_loadavg:
      friendly_name: 'Living Room Accent Lamp 02 LoadAvg'
      unit_of_measurement: '%'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.LoadAvg }}'
    living_room_accent_lamp_02_power:
      friendly_name: 'Living Room Accent Lamp 02 Power'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.POWER }}'
    living_room_accent_lamp_02_dimmer:
      friendly_name: 'Living Room Accent Lamp 02 Dimmer'
      unit_of_measurement: '%'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Dimmer }}'
    living_room_accent_lamp_02_color:
      friendly_name: 'Living Room Accent Lamp 02 Color'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Color }}'
    living_room_accent_lamp_02_hsb_color:
      friendly_name: 'Living Room Accent Lamp 02 HSB Color'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.HSBColor }}'
    living_room_accent_lamp_02_color_channel:
      friendly_name: 'Living Room Accent Lamp 02 Color Channel'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Channel }}'
    living_room_accent_lamp_02_scheme:
      friendly_name: 'Living Room Accent Lamp 02 Scheme'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Scheme }}'
    living_room_accent_lamp_02_fade:
      friendly_name: 'Living Room Accent Lamp 02 Fade'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Fade }}'
    living_room_accent_lamp_02_speed:
      friendly_name: 'Living Room Accent Lamp 02 Speed'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Speed }}'
    living_room_accent_lamp_02_led_table:
      friendly_name: 'Living Room Accent Lamp 02 LED Table'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.LedTable }}'
    living_room_accent_lamp_02_wifi_ssid:
      friendly_name: 'Living Room Accent Lamp 02 Wifi SSId'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Wifi.SSId }}'
    living_room_accent_lamp_02_wifi_ap:
      friendly_name: 'Living Room Accent Lamp 02 Wifi AP'
      value_template: >-
        {% if states.light.living_room_accent_lamp_02.attributes.Wifi.BSSId | string == '30:FD:38:D3:F6:73' %}
          Kitchen AP
        {% elif states.light.living_room_accent_lamp_02.attributes.Wifi.BSSId | string == '30:FD:38:D3:FB:6F' %}
          Office AP
        {% elif states.light.living_room_accent_lamp_02.attributes.Wifi.BSSId | string == '30:FD:38:D3:FB:01' %}
          Workout AP
        {% else %}
          {{ states.light.living_room_accent_lamp_02.attributes.Wifi.BSSId }}
        {% endif %}
    living_room_accent_lamp_02_wifi_bssid:
      friendly_name: 'Living Room Accent Lamp 02 Wifi AP'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Wifi.BSSId }}'
    living_room_accent_lamp_02_wifi_channel:
      friendly_name: 'Living Room Accent Lamp 02 Wifi Channel'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Wifi.Channel }}'
    living_room_accent_lamp_02_wifi_rssi:
      friendly_name: 'Living Room Accent Lamp 02 Wifi RSSI'
      unit_of_measurement: '%'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Wifi.RSSI }}'
    living_room_accent_lamp_02_wifi_linkcount:
      friendly_name: 'Living Room Accent Lamp 02 Wifi Link Count'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Wifi.LinkCount }}'
    living_room_accent_lamp_02_wifi_downtime:
      friendly_name: 'Living Room Accent Lamp 02 Wifi Downtime'
      value_template: '{{ states.light.living_room_accent_lamp_02.attributes.Wifi.Downtime }}'
