- platform: command_line
  name: Raspberry Pi Temperature
  unit_of_measurement: "°C"
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
