- platform: template
  sensors:
    washing_machine_running:
      friendly_name: "Washing Machine Running"
      value_template: >-
        {% if states('sensor.washing_machine_power') | float >= 10.0 %}
          On
        {% else %}
          Off
        {% endif %}
