packages:
  package: !include athom-rgbct-bulb.yaml

substitutions:
  device_name: "foyer-bulb-${num}"
  pretty_name: "Foyer Bulb ${num}"
  light_restore_mode: RESTORE_DEFAULT_ON
  color_interlock: 'true'

esphome:
  on_boot:
    then:
      - light.control:
          id: light_1
          brightness: 90%
          color_temperature: 460 mireds
