- alias: Pantry light timer
  trigger:
    - platform: state
      entity_id: light.pantry_lightswitch
      to: 'on'
      for:
        minutes: 10
  action:
    - service: light.turn_off
      entity_id: light.pantry_lightswitch

- alias: Closet light timer
  trigger:
    - platform: state
      entity_id: light.closet_lightswitch
      to: 'on'
      for:
        minutes: 15
  action:
    - service: light.turn_off
      entity_id: light.closet_lightswitch

- alias: Bathroom light timer
  trigger:
    - platform: state
      entity_id: light.bathroom_lightswitch
      to: 'on'
      for:
        minutes: 90
  action:
    - service: light.turn_off
      entity_id: light.bathroom_lightswitch

- alias: Bathroom shower light timer
  trigger:
    - platform: state
      entity_id: light.bathroom_shower_lightswitch
      to: 'on'
      for:
        minutes: 60
  action:
    - service: light.turn_off
      entity_id: light.bathroom_shower_lightswitch

- alias: Bathroom fan timer
  trigger:
    - platform: state
      entity_id: switch.master_bathroom_fan
      to: 'on'
      for:
        minutes: 60
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom_fan

- alias: Work Bench Lights Auto On/Off
  description: 'Switch workbench lights with basement lights'
  trigger:
    - platform: state
      entity_id: light.basement_lightswitch
  action:
    - service_template: >
        {% if trigger.to_state.state == 'on' %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      entity_id: light.workbench_lights
  mode: single

# - alias: Kodi turn on
#   trigger:
#   - platform: device
#     device_id: e273c89c033011eb96bd238b24b4b6bb
#     domain: kodi
#     entity_id: media_player.living_room_kodi
#     type: turn_on
#   action:
#   - service: light.turn_on
#     entity_id: light.dining_room_lightswitch
#   mode: single