- alias: Pantry light timer
  trigger:
    - platform: state
      entity_id: light.pantry_lightswitch
      to: 'on'
      for:
        minutes: 10
  action:
    - service: light.turn_off
      entity_id: light.pantry_lightswitch

- alias: Closet light timer
  trigger:
    - platform: state
      entity_id: light.closet_lightswitch
      to: 'on'
      for:
        minutes: 15
  action:
    - service: light.turn_off
      entity_id: light.closet_lightswitch

- alias: Bathroom light timer
  trigger:
    - platform: state
      entity_id: light.bathroom_lightswitch
      to: 'on'
      for:
        minutes: 90
  action:
    - service: light.turn_off
      entity_id: light.bathroom_lightswitch

- alias: Bathroom shower light timer
  trigger:
    - platform: state
      entity_id: light.bathroom_shower_lightswitch
      to: 'on'
      for:
        minutes: 60
  action:
    - service: light.turn_off
      entity_id: light.bathroom_shower_lightswitch

- alias: Bathroom fan timer
  trigger:
    - platform: state
      entity_id: switch.master_bathroom_fan
      to: 'on'
      for:
        minutes: 60
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom_fan

- alias: Work Bench Lights Auto On/Off
  description: 'Switch workbench lights with basement lights'
  trigger:
    - platform: state
      entity_id: light.basement_lightswitch
  action:
    - service_template: >
        {% if trigger.to_state.state == 'on' and trigger.from_state.state == 'off' %}
          light.turn_on
        {% elif trigger.to_state.state == 'off' and trigger.from_state.state == 'on' %}
          light.turn_off
        {% endif %}
      entity_id: 
        - light.workbench_lights
        - light.basement_light_001
        - light.basement_light_002
        - light.basement_light_003
        - light.basement_light_004
        - light.basement_light_005
        - light.basement_light_006
        - light.basement_light_007
  mode: single
