<<: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "backyard_lightswitch"
  pretty_name: "Backyard Lightswitch"
  ui_name: "Backyard Motion Sensor"
  icon: "mdi:lghtbulb"