<<: !include common/treatlife_3way_ss02.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "basement_stairs_top_lightswitch"
  pretty_name: "Basement Stairs Top Lightswitch"
  ui_name: "Basement Stairs Light"
  icon: "mdi:lghtbulb"
