<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "basement_lightswitch"
  pretty_name: "Basement Lightswitch"
  ui_name: "Basement Light"
  icon: "mdi:lghtbulb"