packages:
  package: !include common/treatlife_3way_ss01.yaml

substitutions:
  device_name: "basement_stairs_bottom_lightswitch"
  pretty_name: "Basement Stairs Bottom Lightswitch"
  ui_name: "Basement Stairs Bottom Lightswitch"
  icon: "mdi:lghtbulb"
