<<: !include common/wifi.yaml
<<: !include common/sonoff_basic_light.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "basement_light_005"
  pretty_name: "Basement Light 005"
  ui_name: "Basement Light 005"
  icon: "mdi:lghtbulb"
