<<: !include common/wifi.yaml
<<: !include common/sonoff_basic.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "basement_light_001"
  pretty_name: "Basement Light 001"
  ui_name: "Basement Light 001"
  icon: "mdi:lghtbulb"
