<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "basement_lightswitch"
  pretty_name: "Basement Lightswitch"
  switch_ui_name: "Basement Light"
  icon: "mdi:lghtbulb"