<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "basement_light_001"
  pretty_name: "Basement Light 001"
  ui_name: "Basement Light 001"
  icon: "mdi:lghtbulb"
