<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "basement_light_004"
  pretty_name: "Basement Light 004"
  ui_name: "Basement Light 004"
  icon: "mdi:lghtbulb"
