<<: !include common/wifi.yaml
<<: !include common/sonoff_basic_light.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "basement_light_002"
  pretty_name: "Basement Light 002"
  ui_name: "Basement Light 002"
  icon: "mdi:lghtbulb"
