<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "bathroom_lightswitch"
  pretty_name: "Bathroom Lightswitch"
  ui_name: "Bathroom Light"
  icon: "mdi:lghtbulb"