<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s_fan.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "bathroom_fan"
  pretty_name: "Bathroom Fan"
  switch_ui_name: "Bathroom Exhaust Fan"
  icon: "mdi:fan"