<<: !include common/sonoff_s31_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "bedroom_corner_lamp"
  pretty_name: "Bedroom Corner Lamp"
  ui_name: "${pretty_name}"
  icon: "mdi:lamp"
