packages:
  package: !include common/athom-rgbct-bulb.yaml

substitutions:
  device_name: "bedroom-corner-lamp"
  pretty_name: "Bedroom Corner Lamp"
  light_restore_mode: RESTORE_DEFAULT_ON
  color_interlock: 'true'

esphome:
  on_boot:
    then:
      - light.control:
          id: light_1
          brightness: 80%
          color_temperature: 440 mireds
