<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "bedroom_lightswitch"
  pretty_name: "Bedroom Lightswitch"
  ui_name: "Bedroom Light"
  icon: "mdi:lghtbulb"