<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "blue_desk_lamp"
  pretty_name: "Blue Desk Lamp"
  ui_name: "Blue Desk Lamp"
  icon: "mdi:desk-lamp"
