<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "closet_lightswitch"
  pretty_name: "Closet Lightswitch"
  switch_ui_name: "Closet Light"
  icon: "mdi:lghtbulb"