packages:
  package: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "closet_lightswitch"
  pretty_name: "Closet Lightswitch"
  ui_name: "Closet Light"
  icon: "mdi:lghtbulb"