# Based on sonoff_s31_light
<<: !include common/sonoff_s31_light.yaml

substitutions:
  device_name: "dance_studio_spotlights"
  pretty_name: "Dance Studio Spotlights"
  ui_name: "Dance Studio Spotlights"
  icon: "mdi:lamp"
  switch_name: "dance_studio_spotlight_switch"

api:
  services:
    - service: power_toggle
      then:
        - light.toggle:
            id: light_1

# overwriting the light in common/sonoff_s31_light.yaml
light:
  - platform: binary
    name: "${ui_name}"
    id: light_1
    output: relay_1
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - homeassistant.service:
          service: "esphome.${switch_name}_led_on"
    on_turn_off:
      - homeassistant.service:
          service: "esphome.${switch_name}_led_off"
