<<: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "dance_studio_lightswitch"
  pretty_name: "Dance Studio Lightswitch"
  ui_name: "Dance Studio Light"
  icon: "mdi:lghtbulb"