<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "dance_studio_lightswitch"
  pretty_name: "Dance Studio Lightswitch"
  switch_ui_name: "Dance Studio Light"
  icon: "mdi:lghtbulb"