# Based on S31_light
<<: !include common/wifi.yaml
<<: !include common/esp_home_components.yaml
<<: !include common/board_esp01_1m.yaml

substitutions:
  device_name: "dance_studio_spotlights"
  pretty_name: "Dance Studio Spotlights"
  ui_name: "Dance Studio Spotlights"
  icon: "mdi:lamp"

api:
  services:
    - service: power_toggle
      then:
        - light.toggle:
            id: light_1

# Need to turn off the serial logger because we are using the serial
# connection for the power sensors.
logger:
  baud_rate: 0
  level: DEBUG

uart:
  rx_pin: RX
  baud_rate: 4800

status_led:
  pin:
    number: 13
    inverted: True

binary_sensor:
  - name: "${pretty_name} Button"
    platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: False
    on_press:
      - light.toggle: light_1
  - platform: status
    name: "${pretty_name} Status"

output:
  - platform: gpio
    pin:
      number: 12
      inverted: False
    id: relay_1

light:
  - platform: binary
    name: "${ui_name}"
    id: light_1
    output: relay_1
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - homeassistant.service:
          service: esphome.dance_studio_spotlight_switch_led_on
    on_turn_off:
      - homeassistant.service:
          service: esphome.dance_studio_spotlight_switch_led_off

sensor:
  - platform: cse7766
    current:
      name: "${pretty_name} Current"
    voltage:
      name: "${pretty_name} Voltage"
    power:
      name: "${pretty_name} Power"
    update_interval: 10s
  - !include common/wifi_signal.yaml
  - !include common/uptime.yaml
