# Based on SS01s_no_relay
packages: 
  package: !include common/treatlife_ss01s_no_relay.yaml

substitutions:
  device_name: "dance_studio_spotlight_switch"
  pretty_name: "Dance Studio Spotlight Switch"
  ui_name: "Dance Studio Spotlight Switch"
  target_name: "dance_studio_spotlights"

api:
  services:
    - service: led_on
      then:
        - switch.turn_on:
            id: power_led
    - service: led_off
      then:
        - switch.turn_off:
            id: power_led

# overriding common/treatlife_ss01s_no_relay.yaml
binary_sensor:
  - name: "${pretty_name} Button"
    platform: gpio
    pin:
      number: 13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - homeassistant.service:
          service: "esphome.${target_name}_power_toggle"
