packages:
  package: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "dining_room_lightswitch"
  pretty_name: "dining room lightswitch"
  ui_name: "Dining Room Light"
  icon: "mdi:lghtbulb"