<<: !include common/treatlife_3way_ss02.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "dog_room_south_lightswitch"
  pretty_name: "Dog Room South Lightswitch"
  ui_name: "Dog Room South Lightswitch"
  icon: "mdi:lghtbulb"
