<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "driveway_lightswitch"
  pretty_name: "Driveway Lightswitch"
  switch_ui_name: "Driveway Light"
  icon: "mdi:lghtbulb"