<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "driveway_lightswitch"
  pretty_name: "Driveway Lightswitch"
  ui_name: "Driveway Light"
  icon: "mdi:lghtbulb"