<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "first_floor_hall_lightswitch"
  pretty_name: "First Floor Hall Lightswitch"
  ui_name: "First Floor Hall Light"
  icon: "mdi:lghtbulb"