<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "first_floor_hall_lightswitch"
  pretty_name: "First Floor Hall Lightswitch"
  switch_ui_name: "First Floor Hall Light"
  icon: "mdi:lghtbulb"