packages:
  package: !include common/athom-rgbct-bulb.yaml

substitutions:
  device_name: "foyer-bulb-02"
  pretty_name: "Foyer Bulb 02"
  light_restore_mode: RESTORE_DEFAULT_ON
  color_interlock: 'true'

esphome:
  on_boot:
    then:
      - light.control:
          id: light_1
          brightness: 100%
          color_temperature: 359 mireds