packages:
  package: !include common/treatlife_3way_ss01.yaml

substitutions:
  device_name: "foyer_downstairs_lightswitch"
  pretty_name: "Foyer Downstairs Lightswitch"
  ui_name: "Foyer Light"
  icon: "mdi:lghtbulb"
