<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "front_porch_lightswitch"
  pretty_name: "Front Porch Lightswitch"
  switch_ui_name: "Front Porch Light"
  icon: "mdi:lghtbulb"