packages:
  package: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "front_porch_lightswitch"
  pretty_name: "Front Porch Lightswitch"
  ui_name: "Front Porch Light"
  icon: "mdi:lghtbulb"