<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "garage_lightswitch"
  pretty_name: "Garage Lightswitch"
  ui_name: "Garage Light"
  icon: "mdi:lghtbulb"