packages:
  package: !include common/sonoff_s31_switch.yaml

substitutions:
  device_name: "greenhouse_mister"
  pretty_name: "Greenhouse Mister"
  ui_name: "${pretty_name}"
  icon: "mdi:air-humidifier"
