<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "guest_bathroom_lightswitch"
  pretty_name: "Guest Bathroom Lightswitch"
  switch_ui_name: "Guest Bathroom Light"
  icon: "mdi:lghtbulb"