<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s_fan.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "guest bathroom_fan"
  pretty_name: "Guest Bathroom Exhaust Fan"
  ui_name: "Guest Bathroom Exhaust Fan"
  icon: "mdi:fan"