<<: !include common/treatlife_ss01s_fan.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "guest_bathroom_fan"
  pretty_name: "Guest Bathroom Exhaust Fan"
  ui_name: "Guest Bathroom Exhaust Fan"
  icon: "mdi:fan"