<<: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "guest_bathroom_lightswitch"
  pretty_name: "Guest Bathroom Lightswitch"
  ui_name: "Guest Bathroom Light"
  icon: "mdi:lghtbulb"