<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "guest_bedroom_lightswitch"
  pretty_name: "Guest Bedroom Lightswitch"
  ui_name: "Guest Bedroom Light"
  icon: "mdi:lghtbulb"