<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "gym_lightswitch"
  pretty_name: "Gym Lightswitch"
  switch_ui_name: "Gym Light"
  icon: "mdi:lghtbulb"