<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "gym_ceiling_fan"
  pretty_name: "Gym Ceiling Fan"
  switch_ui_name: "Gym Ceiling Fan"
  icon: "mdi:fan"