<<: !include common/treatlife_ss01s_fan.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "gym_ceiling_fan"
  pretty_name: "Gym Ceiling Fan"
  ui_name: "Gym Ceiling Fan"
  icon: "mdi:fan"