<<: !include common/treatlife_ds01_dimmer.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "kitchen_sink_light"
  pretty_name: "Kitchen Sink Light"
  ui_name: "Kitchen Sink Light"
  icon: "mdi:lghtbulb"