<<: !include common/treatlife_ds01_dimmer.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "kitchen_ceiling_lights"
  pretty_name: "Kitchen Ceiling Lights"
  ui_name: "Kitchen Ceiling Lights"
  icon: "mdi:lghtbulb"
