# The dimmer slider for this light will have a quirk in the Home Assistant UI
# where the slider doesn't go below the min_value. To fix this, there's a
# Template Light based on this entity with remapped brightness values.
# See '../lights/kitchen_under_cabinet_lights_dimmer_template.yaml'

<<: !include common/treatlife_ds01_dimmer.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "kitchen_under_cabinet_lightswitch"
  pretty_name: "Kitchen Under Cabinet Lights"
  ui_name: "Kitchen Under Cabinet Lights"
  icon: "mdi:lghtbulb"
