<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "living_room_lamp"
  pretty_name: "Living Room Lamp"
  ui_name: "Living Room Lamp"
  icon: "mdi:floor-lamp"
