packages:
  package: !include common/magichome_rgbw.yaml

substitutions:
  device_name: "living-room-accent-lamp-02"
  pretty_name: "Living Room Accent Lamp 02"
  light_restore_mode: RESTORE_DEFAULT_ON

# esphome:
# on_boot:
#     then:
#     - light.control:
#         id: light_1
