<<: !include common/wifi.yaml
<<: !include common/treatlife_3way_ss02.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "mud_room_west_lightswitch"
  pretty_name: "Mud Room West Lightswitch"
  ui_name: "Mud Room Light West"
  icon: "mdi:lghtbulb"