<<: !include common/treatlife_3way_ss02.yaml

substitutions:
  device_name: "mud_room_east_lightswitch"
  pretty_name: "Mud Room East Lightswitch"
  ui_name: "Mud Room Light"
  icon: "mdi:lghtbulb"