packages:
  package: !include common/robotdyn_ac_dimmer_vent_fan.yaml

substitutions:
  device_name: "office-hvac-booster"
  pretty_name: "Office HVAC Booster"
  ui_name: "Office HVAC Booster"
  icon: "mdi:fan"
