<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "office_lightswitch"
  pretty_name: "Office Lightswitch"
  switch_ui_name: "Office Light"
  icon: "mdi:lghtbulb"
