packages:
  package: !include common/athom-rgbct-bulb.yaml
  den: !include common/packages/den_wifi.yaml

substitutions:
  device_name: "office-lamp-bulb-01"
  pretty_name: "Office Lamp Bulb 01"
  light_restore_mode: RESTORE_DEFAULT_ON
  color_interlock: 'true'

esphome:
  on_boot:
    then:
      - light.control:
          id: light_1
          effect: Rainbowy
