<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "office_lightswitch"
  pretty_name: "Office Lightswitch"
  ui_name: "Office Light"
  icon: "mdi:lghtbulb"
