<<: !include common/wifi.yaml
<<: !include common/sonoff_s31.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "office_hvac_booster"
  pretty_name: "Office HVAC Booster"
  ui_name: "Office HVAC Booster"
  icon: "mdi:fan"
