<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "pantry_lightswitch"
  pretty_name: "Pantry Lightswitch"
  switch_ui_name: "Pantry Light"
  icon: "mdi:lghtbulb"