<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "pantry_lightswitch"
  pretty_name: "Pantry Lightswitch"
  ui_name: "Pantry Light"
  icon: "mdi:lghtbulb"