<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "powder_room_fan"
  pretty_name: "Powder Room Fan"
  switch_ui_name: "Powder Room Fan"
  icon: "mdi:fan"