<<: !include common/wifi.yaml
<<: !include common/treatlife_ss01s_light.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "powder_room_lightswitch"
  pretty_name: "Powder Room Lightswitch"
  ui_name: "Powder Room Light"
  icon: "mdi:lghtbulb"