<<: !include common/treatlife_ss01s_fan.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "powder_room_fan"
  pretty_name: "Powder Room Fan"
  ui_name: "Powder Room Fan"
  icon: "mdi:fan"