packages:
  package: !include common/treatlife_ss01s_light.yaml

substitutions:
  device_name: "powder_room_lightswitch"
  pretty_name: "Powder Room Lightswitch"
  ui_name: "Powder Room Light"
  icon: "mdi:lghtbulb"