# Note: need to use the Adafruit_seesaw files from release 1.3.1
# https://github.com/adafruit/Adafruit_Seesaw/tree/1.3.1
# Based on https://github.com/esphome/feature-requests/issues/720

<<: !include common/wifi.yaml
<<: !include common/esp_home_components.yaml

esphome:
  name: "stemma_test"
  platform: ESP8266
  board: d1_mini
  includes:
    - './includes/stemma/CE_SoilSensor.h'
    - './includes/stemma/Adafruit_seesaw.h'
    - './includes/stemma/Adafruit_seesaw.cpp'

substitutions:
  device_name: "stemma_test"
  pretty_name: "Stemma Test"

sensor:
  - platform: custom
    lambda: |-
        auto SoilSensor = new CE_SoilSensor();
        App.register_component(SoilSensor);
        return  { SoilSensor->TemperatureSensor, SoilSensor->MoistureSensor };
    sensors:
    - name: "Stemma Soil Temperature I2C"
      unit_of_measurement: '°C'
      accuracy_decimals: 1
      filters:
      - median:
          window_size: 10
          send_every: 10
          send_first_at: 10
    - name: "Stemma Soil Moisture I2C"
      filters:
      - median:
          window_size: 10
          send_every: 10
          send_first_at: 10
  - !include ./common/wifi_signal.yaml
  - !include ./common/uptime.yaml
