<<: !include common/sonoff_s31_switch.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "stir_plate"
  pretty_name: "Stir Plate"
  ui_name: "${pretty_name}"
  icon: "mdi:weather-hurricane"
