packages:
  package: !include common/treatlife_3way_ss01.yaml

substitutions:
  device_name: "upstairs_hall_west_lightswitch"
  pretty_name: "Upstairs Hall West Lightswitch"
  ui_name: "Upstairs Hall West Lightswitch"
  icon: "mdi:lghtbulb"
