<<: !include common/wifi.yaml
<<: !include common/sonoff_basic.yaml
<<: !include common/esp_home_components.yaml

substitutions:
  device_name: "vulcan_power"
  pretty_name: "Vulcan Power"
  ui_name: "Vulcan Power"
  # icon: "mdi:lghtbulb"
