<<: !include common/sonoff_s31_switch.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "washing_machine"
  pretty_name: "Washing Machine"
  ui_name: "${pretty_name}"
  icon: "mdi:washing-machine"
