<<: !include common/sonoff_basic_light.yaml
<<: !include common/api.yaml

substitutions:
  device_name: "workbench_lights"
  pretty_name: "Workbench Lights"
  ui_name: "Workbench Lights"
  icon: "mdi:lghtbulb"
